services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    networks:
      - nginx-net
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./mariadb
    networks:
      - db-net
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 2s
        timeout: 20s
        retries: 10
    restart: always
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./wordpress
    networks:
      - db-net
      - nginx-net
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html

networks:
  db-net:
    driver: bridge
  nginx-net:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts: 
      type: none
      device: ${VOLUME_PASS}
      o: bind
  db-data:
    driver: local
    driver_opts: 
      type: none
      device: ${VOLUME_PASS}
      o: bind
